/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pokeoptions_free: (a: number, b: number) => void;
export const pokeoptions_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const __wbg_get_spread_shiny: (a: number) => number;
export const __wbg_set_spread_shiny: (a: number, b: number) => void;
export const __wbg_get_spread_max_dv: (a: number) => number;
export const __wbg_set_spread_max_dv: (a: number, b: number) => void;
export const generate_starters: (a: number) => [number, number];
export const generate_celebi: (a: number) => [number, number];
export const __wbg_randoptions_free: (a: number, b: number) => void;
export const randoptions_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const __wbg_rngstate_free: (a: number, b: number) => void;
export const __wbg_get_rngstate_rand: (a: number) => number;
export const __wbg_set_rngstate_rand: (a: number, b: number) => void;
export const __wbg_get_rngstate_advance: (a: number) => number;
export const __wbg_set_rngstate_advance: (a: number, b: number) => void;
export const __wbg_get_rngstate_add_div: (a: number) => number;
export const __wbg_set_rngstate_add_div: (a: number, b: number) => void;
export const __wbg_get_rngstate_sub_div: (a: number) => number;
export const __wbg_set_rngstate_sub_div: (a: number, b: number) => void;
export const generate_rng_states: (a: number) => [number, number];
export const __wbg_set_spread_state: (a: number, b: number) => void;
export const __wbg_get_spread_advance: (a: number) => number;
export const __wbg_get_spread_state: (a: number) => number;
export const __wbg_set_spread_advance: (a: number, b: number) => void;
export const __wbg_spread_free: (a: number, b: number) => void;
export const __wbindgen_export_0: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
